In [64]:
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import MinMaxScaler
import numpy as np 
import pandas as pd 

pd_data = pd.read_csv('Tracks_8000dp_y1990-2021_full.csv', index_col=0)
labels = pd_data.keys()
data = pd_data.iloc[ :, 3::].to_numpy()
data[0]
pd_data.iloc[ :, 3::].keys()



Index(['danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo'],
      dtype='object')

In [33]:
scaler = MinMaxScaler()
print(scaler.fit(data))
print(scaler.data_max_)
print(scaler.data_min_)
normalized_data = scaler.transform(data)

MinMaxScaler()
[  0.985   0.999  11.      0.457   1.      0.955   0.996   1.      0.996
   0.991 220.099]
[ 0.0000e+00  2.0100e-05  0.0000e+00 -4.7046e+01  0.0000e+00  0.0000e+00
  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00]


In [36]:
print(labels)
normalized_data[0]

Index(['Name', 'Id', 'Year', 'danceability', 'energy', 'key', 'loudness',
       'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo'],
      dtype='object')


array([7.73604061e-01, 7.01695700e-01, 7.27272727e-01, 9.15836895e-01,
       1.00000000e+00, 2.99476440e-02, 2.35943775e-01, 1.58000000e-04,
       1.23493976e-01, 7.48738648e-01, 5.04173122e-01])

In [40]:
nbrs = NearestNeighbors(n_neighbors=4, algorithm='ball_tree').fit(normalized_data)
distances,indices = nbrs.kneighbors(normalized_data)
print(distances, indices)

[[0.         0.10998974 0.14791852 0.17044731]
 [0.         0.         0.         0.        ]
 [0.         0.18311848 0.19155598 0.20396922]
 ...
 [0.         0.19194727 0.20491517 0.22765389]
 [0.         0.14648034 0.18447125 0.18480479]
 [0.         0.23342031 0.26252476 0.27200342]] [[   0 7107 7034 5582]
 [2251  251 2751    1]
 [   2 3518 6517 6649]
 ...
 [7997 7731 6808 6897]
 [7998 1916 1584 6028]
 [7999 3834 5264 3799]]


In [56]:
test_element = normalized_data[200]

distances, neighbors = nbrs.kneighbors([test_element], n_neighbors=5, return_distance=True)
print( 'distances:' ,distances )
print('neighbor indexes:', neighbors)

distances: [[0.         0.26951977 0.36890422 0.37146327 0.43107896]]
neighbor indexes: [[ 200  204 7647 5344 7015]]


In [62]:
similar_tracks = list()
for i in neighbors[0]:
    similar_tracks.append(  pd_data.iloc[i].Id )
similar_tracks

['7C7a42jkuYz4lzVhZuwKZI',
 '30fbS4JTqTphRg2UPn1yyj',
 '31usEzDUXeGWAheRaCeEaD',
 '0WVTQp3SOCuMr08jh1jweV',
 '25U7raB3ZSszayTYClh4hF']